# Generated by Django 5.2.10 on 2026-01-07 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(help_text="Generated care plan text content")),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the downloadable file (S3 key or local path)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="txt", help_text="File format (txt, pdf, docx)", max_length=10
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        help_text="LLM model used for generation",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "llm_prompt_tokens",
                    models.IntegerField(blank=True, help_text="Number of input tokens", null=True),
                ),
                (
                    "llm_completion_tokens",
                    models.IntegerField(blank=True, help_text="Number of output tokens", null=True),
                ),
                (
                    "generation_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Time taken to generate in milliseconds", null=True
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the LLM completed generation", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_plan",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "care_plans",
                "indexes": [
                    models.Index(fields=["order"], name="care_plans_order_i_c28cf1_idx"),
                    models.Index(fields=["generated_at"], name="care_plans_generat_0ca01c_idx"),
                ],
            },
        ),
    ]
