# Generated by Django 5.2.10 on 2026-01-07 06:30

import apps.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "npi",
                    models.CharField(
                        help_text="National Provider Identifier (10 digits)",
                        max_length=10,
                        unique=True,
                        validators=[apps.core.validators.validate_npi],
                    ),
                ),
                ("name", models.CharField(help_text="Provider full name", max_length=200)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, help_text="Fax number", max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "providers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["npi"], name="providers_npi_df1406_idx"),
                    models.Index(fields=["name"], name="providers_name_7e730c_idx"),
                ],
            },
        ),
    ]
