# Generated by Django 5.2.10 on 2026-01-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careplan",
            name="is_uploaded",
            field=models.BooleanField(
                default=False,
                help_text="True if care plan was manually uploaded, False if LLM-generated",
            ),
        ),
        migrations.AddField(
            model_name="careplan",
            name="uploaded_at",
            field=models.DateTimeField(
                blank=True, help_text="When the care plan was manually uploaded", null=True
            ),
        ),
    ]
