# Generated by Django 5.2.10 on 2026-01-07 06:30

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "mrn",
                    models.CharField(
                        help_text="Medical Record Number (6 digits)",
                        max_length=6,
                        unique=True,
                        validators=[apps.core.validators.validate_mrn],
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Patient date of birth", null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("allergies", models.TextField(blank=True, help_text="Known allergies", null=True)),
                (
                    "primary_diagnosis_code",
                    models.CharField(
                        help_text="Primary ICD-10 diagnosis code",
                        max_length=10,
                        validators=[apps.core.validators.validate_icd10],
                    ),
                ),
                (
                    "primary_diagnosis_description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable diagnosis description",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["mrn"], name="patients_mrn_5d1fc1_idx"),
                    models.Index(
                        fields=["last_name", "first_name"], name="patients_last_na_ce6411_idx"
                    ),
                    models.Index(
                        fields=["primary_diagnosis_code"], name="patients_primary_54e862_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("medication_name", models.CharField(max_length=200)),
                (
                    "dosage",
                    models.CharField(
                        blank=True, help_text="e.g., '60 mg'", max_length=100, null=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, help_text="e.g., 'PO q6h PRN'", max_length=100, null=True
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is the patient currently taking this medication?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medication histories",
                "db_table": "medication_history",
                "indexes": [
                    models.Index(fields=["patient"], name="medication__patient_abe94b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientDiagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "icd10_code",
                    models.CharField(
                        max_length=10, validators=[apps.core.validators.validate_icd10]
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient diagnoses",
                "db_table": "patient_diagnoses",
                "indexes": [
                    models.Index(fields=["patient"], name="patient_dia_patient_13836d_idx"),
                    models.Index(fields=["icd10_code"], name="patient_dia_icd10_c_e827c5_idx"),
                ],
            },
        ),
    ]
