# Generated by Django 5.2.10 on 2026-01-07 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Name of the medication being ordered", max_length=200
                    ),
                ),
                (
                    "patient_records",
                    models.TextField(
                        help_text="Clinical notes / patient records for care plan generation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "duplicate_check_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash for duplicate detection",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "confirmed_not_duplicate",
                    models.BooleanField(
                        default=False, help_text="User confirmed this is not a duplicate"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if status is 'failed'", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["patient"], name="orders_patient_702b63_idx"),
                    models.Index(fields=["provider"], name="orders_provide_6df11d_idx"),
                    models.Index(fields=["status"], name="orders_status_762191_idx"),
                    models.Index(fields=["duplicate_check_hash"], name="orders_duplica_183b18_idx"),
                    models.Index(fields=["-created_at"], name="orders_created_b25042_idx"),
                ],
            },
        ),
    ]
