from .base import BaseLLMAdapter

class MockLLMAdapter(BaseLLMAdapter):
    def _call_api(self,prompt: str) -> str:
        return """
        1. Problem List: Mock drug therapy problem...
        2. Goals: Mock SMART goals...
        3. Interventions: Mock pharmacist actions...
        4. Monitoring: Mock monitoring plan...
        """